# Generated by Django 5.1.1 on 2024-12-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group_member'),
        ('members', '0011_alter_member_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='GMember',
        ),
    ]
