# Generated by Django 5.1.1 on 2024-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_member_gmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='coordinated_by',
            field=models.CharField(default='pst. Sharon', max_length=100),
        ),
    ]
