# Generated by Django 5.1.1 on 2024-10-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_secretary',
        ),
    ]
