# Generated by Django 5.1.1 on 2024-10-22 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='baptism_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='baptism_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='date_joined',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_left',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=25),
        ),
        migrations.AddField(
            model_name='member',
            name='member_number',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.CharField(choices=[('regular', 'Regular'), ('associate', 'Associate'), ('guest', 'Guest')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='mobile',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='postal_address',
            field=models.CharField(default='20100', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='residence',
            field=models.CharField(default='Nakuru', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=505.75, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
