# Generated by Django 5.1.1 on 2024-10-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_email_remove_member_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
