# Generated by Django 5.1.1 on 2024-10-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
