# Generated by Django 5.1.1 on 2024-12-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='profile-pics/'),
        ),
    ]
