# Generated by Django 5.1.1 on 2024-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='defaultuser.png', upload_to='profile-pics/'),
        ),
    ]
